-- migrate:up

CREATE EXTENSION IF NOT EXISTS pg_cron;

CREATE ROLE cron_user LOGIN PASSWORD 'secret';

GRANT USAGE ON SCHEMA public TO cron_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cron_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cron_user;

REVOKE ALL ON SCHEMA cron FROM PUBLIC;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA cron FROM PUBLIC;

GRANT USAGE ON SCHEMA cron TO cron_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA cron TO cron_user;

REVOKE ALL ON SCHEMA cron FROM postgres;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA cron FROM postgres;

-- migrate:down

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM cron_user;
REVOKE USAGE ON SCHEMA public FROM cron_user;
REVOKE USAGE ON SCHEMA cron FROM cron_user;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA cron FROM cron_user;
DROP ROLE IF EXISTS cron_user;
DROP EXTENSION IF EXISTS pg_cron CASCADE;